onur/cargo-license

Cargo.toml
src/lib.rs

This takes a string like "MIT/Apache-2.0", splits it into the component
licenses "MIT" and "Apache-2.0", sorts them, and recombines them back into
"Apache-2.0/MIT". This normalization properly groups different packages which
have effectively the same license but word them differently.

Add normalization for multiple licenses

---

README.md
src/cargo-license.rs

I found that bundling the licenses together by type wasn't always ideal. This PR give an option to display info about each crate individually.  An example of the output is:
```
$ cargo-license --do-not-bundle 
advapi32-sys: 0.2.0, "MIT", registry+https://github.com/rust-lang/crates.io-index
aho-corasick: 0.6.3, "MIT/Unlicense", registry+https://github.com/rust-lang/crates.io-index
ansi_term: 0.9.0, "MIT", registry+https://github.com/rust-lang/crates.io-index
backtrace: 0.3.3, "Apache-2.0/MIT", registry+https://github.com/rust-lang/crates.io-index
backtrace-sys: 0.1.16, "Apache-2.0/MIT", registry+https://github.com/rust-lang/crates.io-index
bitflags: 0.7.0, "Apache-2.0/MIT", registry+https://github.com/rust-lang/crates.io-index
bitflags: 0.9.1, "Apache-2.0/MIT", …
```

Add option to display one crate per line

---

Cargo.toml
README.md
src/cargo-license.rs
src/lib.rs

I needed `cargo-license` to build on Fedora 29, and only recent versions of `cargo` have a compatible version of openssl. I used a branch made by @jswrenn as starting point, and then made the following changes:
- Use `cargo_metadata` instead of directly using `cargo` to collect package data. `cargo_metadata` uses a recent version of cargo that does not have the build issue with recent versions of openssl. 
- Use `serde` to optionally output `tsv` or `json`.
- Created a single `DependencyDetails` that maps every detail we might want. This can be output in full using `serde`, or it can be consumed by the existing writer functions in `cargo_license.rs`.
-  `DependencyDetails` will include a link to the source repository when available.
- Replaced `error_chain` with `failure`.
- Since `serde` …

Fix openssl build error, return structured data, extra dependency details

---

Cargo.toml
README.md
src/cargo-license.rs
src/lib.rs

This PR extends some of `cargo_metadata`'s arguments into `cargo-license` like `--features`, `--all-features`, `--no-deps`, `--manifest-path` and `--current-dir`. 
This PR also includes improvements from other PRs.
https://github.com/onur/cargo-license/pull/19 @dnaka91 I included a minor bump for this change.
https://github.com/onur/cargo-license/pull/17 & https://github.com/onur/cargo-license/pull/16 @ErichDonGubler
@onur

Update cargo_metadata, allow feature selection, misc improvements.

---

Cargo.toml
src/lib.rs

This bumps the MSRV to 1.32 because that's what upstream `cargo-metadata` depends upon. None seems to have been specified for this project until now, so this may be a valid reason to discuss before merging or reject outright. Your call!

Update to `cargo_metadata` 0.8.0 from 0.6.3, add `semver` 0.9.0 dep

---

src/main.rs

Drops the extra `license` argument received when being called with `cargo license`.  Additionally, change the binary name displayed in the help message, for uniformity with other Cargo subcommands.  Based on how `cargo-fmt` handles this.
```
$ cargo license --help
cargo-license 0.3.0
Cargo subcommand to see licenses of dependencies.
USAGE:
cargo license [FLAGS] [OPTIONS]
FLAGS:
--all-features     Activate all available features
-a, --authors          Display crate authors
-d, --do-not-bundle    Output one license per line
-h, --help             Prints help information
-j, --json             Detailed output as JSON
--no-deps          Output information only about the root package and don't fetch dependencies
-t, --tsv              Detailed output as tab-separated-values
-V, --version …
```

Improve usage as cargo subcommand

---

src/lib.rs

Instead of printing the dependencies in the order we get them from the
cargo metadata, we sort them by their package names.
This is helpful in situations where you use `cargo-license` to generate
a `NOTICES` file that gets checked into the repository and want to
enfore in CI that the file is up to date.
Since the previous output was in a seemingly random order and the
performance penalty for sorting is rather small, I decided to not hide
this behavior behind a flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onur/cargo-license/26)

Make the order of the output deterministic

---

README.md

This is because anyhow requires Rust 1.34.

Bump MSRV to 1.34

---

src/lib.rs
src/main.rs

Closes #18.
```diff
cargo-license 0.4.0
Cargo subcommand to see licenses of dependencies.
USAGE:
cargo license [FLAGS] [OPTIONS]
FLAGS:
--all-features        Activate all available features
-a, --authors             Display crate authors
+        --avoid-build-deps    Exclude build dependencies
+        --avoid-dev-deps      Exclude development dependencies
-d, --do-not-bundle       Output one license per line
-h, --help                Prints help information
-j, --json                Detailed output as JSON
--no-deps             Output information only about the root package and don't fetch dependencies
-t, --tsv                 Detailed output as tab-separated-values
-V, --version             Prints version information
OPTIONS:
--current-dir <CURRENT_DIR>    Current directory of the …
```

Add `--avoid-dev-deps` and `--avoid-build-deps`

---

src/main.rs

#37 broke the 2 options...
```diff
cargo-license 0.4.0
Cargo subcommand to see licenses of dependencies.
USAGE:
cargo license [FLAGS] [OPTIONS]
FLAGS:
--all-features     Activate all available features
-a, --authors          Display crate authors
-d, --do-not-bundle    Output one license per line
-h, --help             Prints help information
-j, --json             Detailed output as JSON
--no-deps          Output information only about the root package and don't fetch dependencies
-t, --tsv              Detailed output as tab-separated-values
-V, --version          Prints version information
OPTIONS:
-        --CURRENT_DIR <CURRENT_DIR>    Current directory of the cargo metadata process
-        --features <FEATURE>...        Space-separated list of features to activate
-        --PATH …
```

Fix CLI options

---

README.md
src/main.rs

Closes #42
Before
```
./../forks/cargo-license/target/debug/cargo-license --avoid-build-deps --avoid-dev-deps
Apache-2.0 (1): ...
Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT (1): ...
Apache-2.0 OR MIT (38): ...
Apache-2.0 OR MIT OR Zlib (2): ...
MIT (8): ...
```
After
```
../../forks/cargo-license/target/debug/cargo-license --filter-platform x86_64-apple-darwin --avoid-build-deps --avoid-dev-deps
Apache-2.0 (1): ...
Apache-2.0 OR MIT (34): ...
Apache-2.0 OR MIT OR Zlib (2): ...
MIT (8): ...
```

Enable filtering by platform

---

src/main.rs

And fix the 2 warnings seen with pedantic enabled.

Configure clippy to use the same settings as during CI

---

Cargo.toml
README.md
src/lib.rs
src/main.rs

(Either merge #53 first or just merge this one)
The reason I opted to create this little freebie opt is because this is what `--no-deps` would've done on `cargo metadata` directly. However the way `cargo metadata` handles ` --no-deps` breaks this crate, therefore we implement a little bit of custom logic to handle this case ourselves.

add `--root-only`

---

src/main.rs

Implementing suggestion on #51, but opting to be a bit more verbose and call it "Custom License File", this is because an invalidly set license in the `license` field will still overwrite this.

"Custom License File" instead of "N/A" (fixes #51)

---

Cargo.toml
README.md
src/lib.rs
src/main.rs

Allows cargo-license to output json file compatible with https://docs.gitlab.com/ee/user/compliance/license_compliance/
(Current Gitlab's tooling for license scanning in Rust projects is broken, with no fix on sight)
Output was tested on private project and works well :)

feat: Support for gitlab license scanning report

---

Cargo.toml
src/main.rs

This PR updates the clap dependency and removed the [unmainted](https://rustsec.org/advisories/RUSTSEC-2021-0145) `atty` dependency.
`atty` is replaced with the use of `std::io::IsTerminal`, stable since `rust` 1.70.

Migrate to clap v4 and remove atty dependency

---

Cargo.toml
README.md

This PR bumps MSRV to 1.70.
This is because `std::io::IsTerminal` and clap v4 require Rust 1.70.
Related: #64

Bump MSRV to 1.70

---

src/main.rs

The default help style of clap v4 (#64 ) was changed from v3.
This PR adjust the style to the same as v3.

Adjust help style

---

src/lib.rs
src/main.rs

I found some discussion about this in https://github.com/onur/cargo-license/pull/38.
Used on this crate, it filters out 
`"serde_derive", "quote", "clap_derive", "serde", "syn", "heck", "proc-macro2", "thiserror-impl"`

Add `--avoid-proc-macros`.

---

src/main.rs

Before this, doing things like:
```bash
cargo license | grep '^Apache'
```
would not work, as the colors would interfere with grepping.

Auto color stdout based, not stdin

---

Cargo.toml
README.md

This PR bumps MSRV to 1.86.
This is because spdx requires 2024 edition, and cargo-metadata requires Rust 1.86.

Bump MSRV to 1.86
